### ISSUE TITLE
Pagination does not worked, passing title in search params

### ISSUE THREAD

**Issue by aldrienht** [hi5dev/shopify-kaminari#8]
**Gem info:**

```
shopify-kaminari (1.1.0)
shopify_api (4.3.2 494b37a)
shopify_app (7.4.0)
```
**Request:**

```
parameters = {fields: 'id,title,url,handle', page: params[:page] || 1, limit: 5}
parameters = parameters.merge(title: params[:title]) if params[:title].present?

@products = ShopifyAPI::Product.find(:all, params: parameters)
```
Query works well without `title` as additional search params.

**Issue:**
When requesting **WITH** filter for title, result (ShopifyAPI::Product instance) seems doesn't return total_count or some other issue.

Pagination doesn't worked, doesn't show in view.

**Comment by travishaynes** [comment]
Shopify moved away from this type of pagination. They now use cursor-based pagination.

https://shopify.dev/changelog/page-based-pagination-replaced-by-cursor-based-pagination-across-multiple-rest-endpoints

I see you're using version 4.3.2 of the shopify_api gem. You really need to update your app. Page-based pagination will be completely removed from the API soon.
